export var suggestions = [
{ label: 'American Chinese cuisine' },
{ label: 'Biscuit' },
{ label: 'Bread' },
{ label: 'Ammonia cookie' },
{ label: 'Apple butter' },
{ label: 'Apple sauce' },
{ label: 'Baked potato' },
{ label: 'Barbecue' },
{ label: 'Bear claw' },
{ label: 'Beef Manhattan' },
{ label: 'Blue cheese dressing' },
{ label: 'Blue-plate special' },
{ label: 'Bookbinder soup' },
{ label: 'Breakfast burrito' },
{ label: 'Brunswick stew' },
{ label: 'Buffalo burger' },
{ label: 'Buffalo wing' },
{ label: 'Bull roast' },
{ label: 'Burnt ends' },
{ label: 'Butter cookie' },
{ label: 'Cajun cuisine' },
{ label: 'Calfs liver and bacon' },
{ label: 'Carolina style' },
{ label: 'Celery Victor' },
{ label: 'Cheese dog' },
{ label: 'Cheese fries' },
{ label: 'Cheese steak' },
{ label: 'Chicago-style_pizza' },
{ label: 'Chicken à la King' },
{ label: 'Chicken and waffles' },
{ label: 'Chicken Divan' },
{ label: 'Chicken fingers' },
{ label: 'Chicken French' },
{ label: 'Chicken fried bacon' },
{ label: 'Chicken fried steak' },
{ label: 'Chicken nugget' },
{ label: 'Chicken parmigiana' },
{ label: 'Chicken sandwich' },
{ label: 'Chili con carne' },
{ label: 'Chili dog' },
{ label: 'Chimichanga' },
{ label: 'Chips and dip' },
{ label: 'Dark chocolate' },
{ label: 'Milk chocolate' },
{ label: 'White chocolate' },
{ label: 'Chocolate chip cookies' },
{ label: 'Choco pie' },
{ label: 'Chowder' },
{ label: 'City chicken' },
{ label: 'Clam cake' },
{ label: 'Clam chowder' },
{ label: 'Coleslaw' },
{ label: 'Cordon bleu' },
{ label: 'Corn chowder' },
{ label: 'Corn dog' },
{ label: 'Corn flakes' },
{ label: 'Corn relish' },
{ label: 'Corned beef' },
{ label: 'Cornish game hen' },
{ label: 'Cowboy beans' },
{ label: 'Crab cake' },
{ label: 'Creamed corn' },
{ label: 'Creamed eggs on toast' },
{ label: 'Deviled crab' },
{ label: 'Deviled egg' },
{ label: 'Domesticated turkey' },
{ label: 'Doughnut' },
{ label: 'Drunken chicken' },
{ label: 'Eggo' },
{ label: 'Eggs Benedict' },
{ label: 'Eggs Neptune' },
{ label: 'Energy bar' },
{ label: 'Turducken' },
{ label: 'Fajita' },
{ label: 'Fortune cookie' },
{ label: 'French dip' },
{ label: 'Fried chicken' },
{ label: 'Fried fish' },
{ label: 'Fry sauce' },
{ label: 'Frybread' },
{ label: 'Garden salad' },
{ label: 'German chocolate cake' },
{ label: 'Goulash' },
{ label: 'Greek-American cuisine' },
{ label: 'Green bean casserole' },
{ label: 'Grits' },
{ label: 'Hamburger' },
{ label: 'Hangtown fry' },
{ label: 'Haystack' },
{ label: 'Hog fry' },
{ label: 'Home fries' },
{ label: 'Hot chicken' },
{ label: 'Hot chicken sandwich' },
{ label: 'Ice cream cake' },
{ label: 'Italian-American cuisine' },
{ label: 'Italian beef' },
{ label: 'Italian dressing' },
{ label: 'Jell-O' },
{ label: 'Jerky' },
{ label: 'Juba' },
{ label: 'Liver and onions' },
{ label: 'Lobster Newberg' },
{ label: 'Lobster roll' },
{ label: 'London broil' },
{ label: 'Lorna Doone' },
{ label: 'Macaroni and cheese' },
{ label: 'Macaroni salad' },
{ label: 'Maple bacon donut' },
{ label: 'Maraca pie' },
{ label: 'Mashed potato' },
{ label: 'Mashed pumpkin' },
{ label: 'Meatcake' },
{ label: 'Meatloaf' },
{ label: 'Milk toast' },
{ label: 'Milkshake' },
{ label: 'Mission burrito' },
{ label: 'Mozzarella sticks' },
{ label: 'Muffuletta' },
{ label: 'Mulligan stew' },
{ label: 'Onion ring' },
{ label: 'Oreo' },
{ label: 'Oysters Rockefeller' },
{ label: 'Pancakes' },
{ label: 'Pasta salad' },
{ label: 'Pastrami' },
{ label: 'Patty' },
{ label: 'Peanut butter' },
{ label: 'Pemmican' },
{ label: 'Pepperoni' },
{ label: 'Philadelphia Cheese steak' },
{ label: 'Pickled cucumber' },
{ label: 'Pigs in blankets' },
{ label: 'Pizza strips' },
{ label: 'Ploye' },
{ label: 'Pop-Tarts' },
{ label: 'Popcorn' },
{ label: 'Popover' },
{ label: 'Poppyseed muffin' },
{ label: 'Pork and beans' },
{ label: 'Potato salad' },
{ label: 'Potato skins' },
{ label: 'Potato wedges' },
{ label: 'Potatoes OBrien' },
{ label: 'Protein bar' },
{ label: 'Pulled pork' },
{ label: 'Pumpkin pie' },
{ label: 'Rabbit pie' },
{ label: 'Ranch dressing' },
{ label: 'Reuben sandwich' },
{ label: 'Ribs' },
{ label: 'Rolled oyster' },
{ label: 'Russian dressing' },
{ label: 'Russian tea cake' },
{ label: 'Salisbury steak' },
{ label: 'Sandwich' },
{ label: 'Sausage gravy' },
{ label: 'Scampi' },
{ label: 'Scrapple' },
{ label: 'Seafood cocktail' },
{ label: 'Senate bean soup' },
{ label: 'Slinger' },
{ label: 'Sloppy joe' },
{ label: 'Smelt' },
{ label: 'Sonofabitch stew' },
{ label: 'Soul food' },
{ label: 'Sour cream' },
{ label: 'Squab' },
{ label: 'Steak' },
{ label: 'Steak sandwich' },
{ label: 'Steak sauce' },
{ label: 'Steamed clams' },
{ label: 'Stuffed ham' },
{ label: 'Stuffed peppers' },
{ label: 'Stuffed zucchini' },
{ label: 'Succotash' },
{ label: 'Surf and turf' },
{ label: 'Swiss steak' },
{ label: 'Tetrazzini' },
{ label: 'Cuisine of the Thirteen Colonies' },
{ label: 'Thousand Island dressing' },
{ label: 'Toaster Strudel' },
{ label: 'Tomato compote' },
{ label: 'Tuna casserole' },
{ label: 'Turducken' },
{ label: 'Thanksgiving turkey' },
{ label: 'Vichyssoise' },
{ label: 'Waffle' }
]
// export suggestions;
